version: '3.8'

services:

  wordpress:
    image: wordpress
    restart: always
    container_name: wordpress
    # ports:
    #   - 80:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - wordpress:/var/www/html
    networks:
      - proxy

  db:
    image: mysql:5.7
    restart: always
    container_name: mydb
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql
    networks:
      - proxy

volumes:
  wordpress:
    name: 'wordpress'
  db:
    name : db

networks:
  proxy:
    external: true
    name: proxy