version: "3.5"

networks:
  proxy:
    external: true
    name: proxy

volumes:
  letsencrypt:
  cronstamps:

services:
  proxy:
    image: haproxy:latest
    restart: always
    volumes:
      - ./haproxy:/usr/local/etc/haproxy:ro
      - ./certs:/usr/local/etc/certs:ro
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      - target: 1936
        published: 1936
        protocol: tcp
        mode: host
    networks:
      - proxy
    deploy:
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure

  nginx-certbot:
    image: nginx
    restart: always
    container_name: nginx-certbot
    volumes:
      - ./webroot:/usr/share/nginx/html
    networks:
      - proxy